# Generated by Django 4.2.6 on 2023-11-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заявки')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('image', models.ImageField(upload_to='image/%Y', verbose_name='Изображение помещения')),
                ('status', models.CharField(choices=[('New', 'новая'), ('Done', 'выполненная'), ('employed', 'принятая в работу')], default='New', max_length=254, verbose_name='Статус')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='design_studio.category')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
