# Generated by Django 4.2.6 on 2023-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('2D', '2D-дизайн'), ('3D', '3D-дизайн'), ('not-stated', 'не известно')], default='not-stated', max_length=254, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Название заявки')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('image', models.ImageField(upload_to='image/%Y', verbose_name='Изображение помещения')),
                ('status', models.CharField(choices=[('New', 'новая'), ('Done', 'выполненная'), ('employed', 'принятая в работу')], default='New', max_length=254, verbose_name='Статус')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('approval', models.BooleanField(verbose_name='Согласие на обработку персональных данных')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
