# Generated by Django 4.2.6 on 2023-11-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approval',
        ),
    ]
