# Generated by Django 4.2.6 on 2023-11-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0002_alter_category_options_alter_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default='2023-11-21', verbose_name='Дата публикации'),
        ),
    ]
