# Generated by Django 4.2.6 on 2023-11-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0004_alter_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название категории'),
        ),
    ]
