# Generated by Django 4.2.6 on 2023-11-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_studio', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='design_studio.category', verbose_name='Категория'),
        ),
    ]
